export const LOAD_PROFILES = 'LOAD_PROFILES';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const MANIPULATE_CARROTS = 'MANIPULATE_CARROTS';
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';